apiVersion: v2
name: kagent-crds
description: CRDs for kagent
type: application
version: 0.8.3
dependencies:
  - name: kmcp-crds
    version: 0.2.8
    repository: oci://ghcr.io/kagent-dev/kmcp/helm
    condition: kmcp.enabled
